sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Wjp7867137639
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tQBdVd1PJT2CJSTJQLK
    access-key-secret: wEaar1GnTpVTvptnXTEMTd6Sf1eTJW
    bucket-name: daykalif-sky-itcast
  redis:
    host: localhost
    port: 6379
    password:
    database: 10 # redis有16个数据库，默认是0号数据库
  wechat:
    appid: wx6c21d4adb27d7803
    secret: 456bcea4f9267366e4c36890a4752aac
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\pay\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://58869fb.r2.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://58869fb.r2.cpolar.top/notify/refundSuccess


# 阿里云配置access-key文档：https://help.aliyun.com/zh/direct-mail/configure-the-authentication-accesskey-in-the-environment-variable