sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Wjp7867137639
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: daykalif-sky-itcast


# 阿里云配置access-key文档：https://help.aliyun.com/zh/direct-mail/configure-the-authentication-accesskey-in-the-environment-variable