sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Wjp7867137639
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: xxxx
    access-key-secret: xxxx
    bucket-name: daykalif-sky-itcast